// Generated by https://quicktype.io (some parts were also written manually)
// this entire thing was written manually but i don't want to remove that because it is history
// well at least history from back when i barely knew typescript

export interface Status {
    status: string;
    char: string;
}

export interface UserData {
    name: string;
    email: string;
    id: string;
    img: string;
    status?: Status;
    schedule?: string[];
}

export enum OnlineStatus {
    online = "ONLINE",
    offline = "OFFLINE",
    idle = "IDLE"
}

export interface OnlineUserData extends UserData {
    online: OnlineStatus;
}
export interface UserAuth {
    salt: string;
    name: string;
    hash: string;
    deviceIds: string[];
}
export interface UserAuths {
    [key: string]: UserAuth;
}

/**
 * @deprecated Use UserAuth/UserData instead
 */
export interface AuthData2 {
    name: string;
    email: string;
    mpid: string;
}

/**
 * @deprecated Use AuthData2 instead
 */
export interface AuthData {
    name: string;
    authname: string;
    cdid: string;
}
