// Generated by https://quicktype.io (some parts were also written manually)

export interface UserData {
    name: string;
    email: string;
    id: string;
    img: string;
}
export interface UserAuth {
    salt: string;
    name: string;
    hash: string;
    deviceIds: string[];
}
export interface UserAuths {
    [key: string]: UserAuth;
}

/**
 * @deprecated Use UserAuth/UserData instead
 */
export interface AuthData2 {
    name: string;
    email: string;
    mpid: string;
}

/**
 * @deprecated Use AuthData2 instead
 */
export interface AuthData {
    name: string;
    authname: string;
    cdid: string;
}
