// Generated by https://quicktype.io

export default interface AuthData2 {
    name:     string;
    email: string;
    mpid:     string;
}

export interface AuthData {
    name:     string;
    authname: string;
    cdid:     string;
}
