// Generated by https://quicktype.io

export default interface Users {
    emails:    string[];
    names:     { [key: string]: string };
    authnames: Authnames;
    images:    Authnames;
}

export interface Authnames {
    "Jason Mayer":      string;
    "jonathan mayer":   string;
    "Emily Mayer":      string;
    "Dominic Cottrill": string;
    "Felix Singer":     string;
    "Oliver Boyden":    string;
    "Theodore Hill":    string;
    "Tyler Ricks":      string;
    "Liam Bruch":       string;
}
