// Generated by https://quicktype.io

export default interface Users {
    emails:     string[];
    alt_emails: { [key: string]: string };
    names:      { [key: string]: string };
    images:     Images;
}

export interface Images {
    "Jason Mayer":      string;
    "jonathan mayer":   string;
    "Emily Mayer":      string;
    "Dominic Cottrill": string;
    "Felix Singer":     string;
    "Oliver Boyden":    string;
    "Theodore Hill":    string;
    "Tyler Ricks":      string;
    "Liam Bruch":       string;
}
