[package]
name = "backup-service"
version = "1.0.0"
edition = "2021"
publish = false
authors = ["Jason Mayer <jason@baydq.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ftp = "3.0.1"
json = "0.12.4"
chrono = "0.4.31"